name: Install Node Dependencies
description: Install Node Dependencies
runs:
  using: composite
  steps:
    - name: Get npm Cache Directory
      id: npm-cache-dir
      shell: bash
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node Dependencies
      shell: bash
      run: npm ci
